server:
  port: 40200
spring:
  application:
    name: xc-service-send
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
  #邮箱发送的配置 网易的配置要加from参数
  mail:
    host: smtp.qq.com
    #邮箱账号
    username: xuecheng.mail@qq.com
    #邮箱密码或授权码
    password: erbtpneusweygdef
    #协议
    protocol: smtp
    #这里换成自己的邮箱类型 例如qq邮箱就写smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: aaa #可以任意
    properties.mail.display.sendname: bbb #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true #开启SSL
    default-encoding: utf-8

eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer‐ip‐address: true #将自己的ip地址注册到Eureka服务中
    ip‐address: ${IP_ADDRESS:127.0.0.1}
    instance‐id: ${spring.application.name}:${server.port} #指定实例id
    hostname: ${EUREKA_DOMAIN:eureka01}

  freemarker:
    cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
    suffix: .html # 模版后缀名 默认为ftl
    charset: UTF-8 # 文件编码
    template-loader-path: classpath:/templates/  # 存放模板的文件夹，以resource文件夹为相对路径
aliyun:
  accessKeyID: LTAI4G3XcFwmsbBhhXJZv567
  accessKeySecret: LMl75HCr5J8Tmt42afrSZjNE9DSR23

