server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://root:123456@localhost:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
xc-service-manage-media:
  mq:
    # 注册的队列
    queue-media-video-processor: queue_media_video_processor
    # 绑定的路由key
    routingkey-media-video: routingkey_media_video
  video-location: F:/study/xcEdu/xcEduUI/video/
  ffmpeg-path: D:/tools/ffmpeg/bin/ffmpeg.exe
