server:
  port: 31003
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri:  mongodb://root:123456@localhost:27017
      database: xc_cms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
xuecheng:
  mq:
    #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue01: queue_cms_postpage_01
    routingKey01: 5a751fab6abb5044e0d19ea1	#此routingKey为门户站点ID

    #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue02: queue_cms_postpage_02
    routingKey02: 5cfe61c5619b3b11280bf0b3    #此routingKey为课程预览站点ID